x = int(input("Please tell me your age: "))
print("You are currently",x,"years old.")
print("In 10 years, you'll be",(x+10),"years old.")
print("In 20 years, you'll be",(x+20),"years old.")
print("In 3160 years, you'll be",(x+30),"years old.")